[project]
name = 'Xenolinguistics-Development-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bci-integration]
path = 'contracts/bci-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.consciousness-governance]
path = 'contracts/consciousness-governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.consciousness-storage]
path = 'contracts/consciousness-storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.consciousness-token]
path = 'contracts/consciousness-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.consciousness-transfer]
path = 'contracts/consciousness-transfer.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
